// Generated by gencpp from file robot/inv.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_INV_H
#define ROBOT_MESSAGE_INV_H

#include <ros/service_traits.h>


#include <robot/invRequest.h>
#include <robot/invResponse.h>


namespace robot
{

struct inv
{

typedef invRequest Request;
typedef invResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inv
} // namespace robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot::inv > {
  static const char* value()
  {
    return "8124fdf484553a52e7b685afd1f774e4";
  }

  static const char* value(const ::robot::inv&) { return value(); }
};

template<>
struct DataType< ::robot::inv > {
  static const char* value()
  {
    return "robot/inv";
  }

  static const char* value(const ::robot::inv&) { return value(); }
};


// service_traits::MD5Sum< ::robot::invRequest> should match
// service_traits::MD5Sum< ::robot::inv >
template<>
struct MD5Sum< ::robot::invRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot::inv >::value();
  }
  static const char* value(const ::robot::invRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::invRequest> should match
// service_traits::DataType< ::robot::inv >
template<>
struct DataType< ::robot::invRequest>
{
  static const char* value()
  {
    return DataType< ::robot::inv >::value();
  }
  static const char* value(const ::robot::invRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot::invResponse> should match
// service_traits::MD5Sum< ::robot::inv >
template<>
struct MD5Sum< ::robot::invResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot::inv >::value();
  }
  static const char* value(const ::robot::invResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::invResponse> should match
// service_traits::DataType< ::robot::inv >
template<>
struct DataType< ::robot::invResponse>
{
  static const char* value()
  {
    return DataType< ::robot::inv >::value();
  }
  static const char* value(const ::robot::invResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MESSAGE_INV_H
